apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-cephfs-ctrlplugin-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-cephfs-nodeplugin-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-controller-manager
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-nfs-ctrlplugin-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-nfs-nodeplugin-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-rbd-ctrlplugin-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-csi-rbd-nodeplugin-sa
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
