apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ceph-csi-cephfs-ctrlplugin-rb
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-csi-cephfs-ctrlplugin-r
subjects:
  - kind: ServiceAccount
    name: ceph-csi-cephfs-ctrlplugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ceph-csi-cephfs-nodeplugin-rb
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-csi-cephfs-nodeplugin-r
subjects:
  - kind: ServiceAccount
    name: ceph-csi-cephfs-nodeplugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ceph-csi-leader-election-rolebinding
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-csi-leader-election-role
subjects:
  - kind: ServiceAccount
    name: ceph-csi-controller-manager
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ceph-csi-rbd-ctrlplugin-rb
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-csi-rbd-ctrlplugin-r
subjects:
  - kind: ServiceAccount
    name: ceph-csi-rbd-ctrlplugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ceph-csi-rbd-nodeplugin-rb
  namespace: {{ .Values.rookConfig.rookNamespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-csi-rbd-nodeplugin-r
subjects:
  - kind: ServiceAccount
    name: ceph-csi-rbd-nodeplugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
