apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ceph-csi-cephfs-ctrlplugin-crb
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ceph-csi-cephfs-ctrlplugin-cr
subjects:
  - kind: ServiceAccount
    name: ceph-csi-cephfs-ctrlplugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ceph-csi-cephfs-nodeplugin-crb
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ceph-csi-cephfs-nodeplugin-cr
subjects:
  - kind: ServiceAccount
    name: ceph-csi-cephfs-nodeplugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ceph-csi-manager-rolebinding
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ceph-csi-manager-role
subjects:
  - kind: ServiceAccount
    name: ceph-csi-controller-manager
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ceph-csi-metrics-auth-rolebinding
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ceph-csi-metrics-auth-role
subjects:
  - kind: ServiceAccount
    name: ceph-csi-controller-manager
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ceph-csi-nfs-ctrlplugin-crb
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ceph-csi-nfs-ctrlplugin-cr
subjects:
  - kind: ServiceAccount
    name: ceph-csi-nfs-ctrlplugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ceph-csi-nfs-nodeplugin-crb
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ceph-csi-nfs-nodeplugin-cr
subjects:
  - kind: ServiceAccount
    name: ceph-csi-nfs-nodeplugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ceph-csi-rbd-ctrlplugin-crb
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ceph-csi-rbd-ctrlplugin-cr
subjects:
  - kind: ServiceAccount
    name: ceph-csi-rbd-ctrlplugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ceph-csi-rbd-nodeplugin-crb
  labels:
{{ include "chart.labels" . | indent 4 }}
{{ include "ceph-csi-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ceph-csi-rbd-nodeplugin-cr
subjects:
  - kind: ServiceAccount
    name: ceph-csi-rbd-nodeplugin-sa
    namespace: {{ .Values.rookConfig.rookNamespace }}
