---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: cephdeploymentsecrets.lcm.mirantis.com
spec:
  group: lcm.mirantis.com
  names:
    kind: CephDeploymentSecret
    listKind: CephDeploymentSecretList
    plural: cephdeploymentsecrets
    shortNames:
    - cephdplsecret
    singular: cephdeploymentsecret
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: Secret state
      jsonPath: .status.state
      name: State
      type: string
    - description: Last secret update
      jsonPath: .status.lastSecretCheck
      name: Last check
      type: string
    - description: Last secret update
      jsonPath: .status.lastSecretUpdate
      name: Last update
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CephDeploymentSecret aggregates secrets created by Ceph
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          status:
            description: Status contains overall status and secrets info for MiraCephSecret
            properties:
              lastSecretCheck:
                description: LastUpdate is a last time when MiraCephSecret was updated
                nullable: true
                type: string
              lastSecretUpdate:
                description: LastUpdate is a last time when MiraCephSecret was updated
                nullable: true
                type: string
              messages:
                description: Messages is a list with any possible error/warning messages
                items:
                  type: string
                type: array
              secretInfo:
                description: SecretsInfo contains Ceph secret names for related objects
                properties:
                  clientSecrets:
                    description: ClientSecrets list of secrets info for ceph clients
                    items:
                      description: CephDeploymentSecretInfo contains secret name,
                        namespace and object name, associated with secret
                      properties:
                        name:
                          type: string
                        secretName:
                          type: string
                        secretNamespace:
                          type: string
                      required:
                      - name
                      - secretName
                      - secretNamespace
                      type: object
                    type: array
                  rgwUserSecrets:
                    description: RgwUserSecrets list of secrets info for ceph radosgw
                      users
                    items:
                      description: CephDeploymentSecretInfo contains secret name,
                        namespace and object name, associated with secret
                      properties:
                        name:
                          type: string
                        secretName:
                          type: string
                        secretNamespace:
                          type: string
                      required:
                      - name
                      - secretName
                      - secretNamespace
                      type: object
                    type: array
                type: object
              state:
                description: State represents the state for overall secret status
                type: string
            required:
            - state
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
