name: Build E2E CI

on:
  push:
    branches: [ "main", "release-*" ]
    tags: ['*']
    paths:
    - 'pkg/apis/**'
    - 'test/e2e/**'
    - 'go.mod'
    - 'e2e.Dockerfile'
    - 'e2e.mk'
    - 'Makefile'
  pull_request:
    branches: [ "main", "release-*" ]
    paths:
    - 'pkg/apis/**'
    - 'test/e2e/**'
    - 'go.mod'
    - 'e2e.Dockerfile'
    - 'e2e.mk'
    - 'Makefile'

# abort in progress when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  build-e2e:
    runs-on: ubuntu-latest
    env:
      CI_E2E_IMAGE_NAME: ${{ github.event_name == 'pull_request' && format('{0}/pelagia/pr/pelagia-e2e', vars.REGISTRY_CI) || format('{0}/pelagia/pelagia-e2e', vars.REGISTRY_CI) }}
      DEV_VERSION: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Check lint
        run: make lint
      - name: Set image version
        run: |
          echo IMAGE_TAG=$(make get-version) >> $GITHUB_ENV
      - name: Login to registry CI
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_CI }}
          username: ${{ secrets.REGISTRY_CI_USERNAME }}
          password: ${{ secrets.REGISTRY_CI_PASSWORD }}
      - name: Login to main registry
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_PROD }}
          username: ${{ secrets.REGISTRY_PROD_USERNAME }}
          password: ${{ secrets.REGISTRY_PROD_PASSWORD }}
      - name: Set e2e image multibuild output for CI
        if: ${{ github.ref_type != 'tag' }}
        run: |
          echo IMAGE_E2E_MULTIBUILD_OUTPUT='type=image,name=${{ env.CI_E2E_IMAGE_NAME }}:${{ env.IMAGE_TAG }},push=true' >> $GITHUB_ENV
      - name: Set e2e image multibuild output for release
        if: ${{ github.ref_type == 'tag' }}
        env:
          RELEASE_E2E_IMAGE_NAME: ${{ format('{0}/pelagia/pelagia-e2e', vars.REGISTRY_PROD) }}
        run: |
          echo IMAGE_E2E_MULTIBUILD_OUTPUT='type=image,name=${{ env.CI_E2E_IMAGE_NAME }}:${{ env.IMAGE_TAG }},push=true type=image,name=${{ env.RELEASE_E2E_IMAGE_NAME }}:${{ env.IMAGE_TAG }},push=true' >> $GITHUB_ENV
      - name: Run image build and push to registry
        run: make docker.build/e2e
