name: Golang CI

on:
  push:
    branches: [ "main", "release-**" ]
  pull_request:
    branches: [ "main", "release-**" ]

# abort in progress when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  go-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'
      - name: Display Go version
        run: go version
      - name: Run Go linter
        run: make check && make check-diff

  units:
    runs-on: ubuntu-latest
    needs: go-linter
    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'
      - name: Display Go version
        run: go version
      - name: Run Go unit
        run: make unit
