name: Helm CI

on:
  push:
    branches: [ "main", "release-*" ]
    paths:
    - 'chart/**'
    - 'Makefile'
  pull_request:
    branches: [ "main", "release-*" ]
    paths:
    - 'chart/**'
    - 'Makefile'

# abort in progress when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  helm-check:
    runs-on: ubuntu-latest
    env:
      BUILD_MODE: ${{ github.event_name == 'push' && 'merge' || 'dev' }}
      DEV_VERSION: ${{ github.event_name == 'pull_request' && github.event.pull_request.number }}
      HELM_REPO: ${{ github.event_name == 'push' && 'pelagia' || 'pelagia/pr' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1
        with:
          version: v3.18.2
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - name: Show current version
        run: make get-version
      - name: Run helm package
        run: make
      - name: Login to registry CI
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_CI }}
          username: ${{ secrets.REGISTRY_CI_USERNAME }}
          password: ${{ secrets.REGISTRY_CI_PASSWORD }}
      - name: Push Helm chart
        run: |
          for pkg in ./pelagia-ceph-*.tgz; do
            helm push ${pkg} oci://${{ vars.REGISTRY_CI }}/${{ env.HELM_REPO }}
          done
