name: Helm CI

on:
  push:
    branches: [ "main", "release-*" ]
    tags: ['*']
    paths:
    - 'charts/**'
    - 'Makefile'
  pull_request:
    branches: [ "main", "release-*" ]
    paths:
    - 'charts/**'
    - 'Makefile'

# abort in progress when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  helm-check:
    runs-on: ubuntu-latest
    env:
      DEV_VERSION: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || '' }}
      HELM_REPO: ${{ github.event_name == 'push' && 'pelagia' || 'pelagia/pr' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1
        with:
          version: v3.18.2
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - name: Show current version
        run: make get-version
      - name: Run helm package
        run: make
      - name: Login to registry CI
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_CI }}
          username: ${{ secrets.REGISTRY_CI_USERNAME }}
          password: ${{ secrets.REGISTRY_CI_PASSWORD }}
      - name: Push Helm chart to registry CI
        env:
          HELM_REGISTRY: oci://${{ vars.REGISTRY_CI }}/${{ env.HELM_REPO }}
        run: make publish-chart
      - name: Login to main registry
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_PROD }}
          username: ${{ secrets.REGISTRY_PROD_USERNAME }}
          password: ${{ secrets.REGISTRY_PROD_PASSWORD }}
      - name: Push Helm chart to main registry
        if: ${{ github.ref_type == 'tag' }}
        env:
          HELM_REGISTRY: oci://${{ vars.REGISTRY_PROD }}/${{ env.HELM_REPO }}
        run: make publish-chart
