name: Helm CI

on:
  push:
    branches: [ "main", "release-**" ]
    paths:
    - 'chart/**'
    - 'Makefile'
  pull_request:
    branches: [ "main", "release-**" ]
    paths:
    - 'chart/**'
    - 'Makefile'

# abort in progress when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  helm-check:
    runs-on: ubuntu-latest
    env:
      BUILD_MODE: ${{ github.event_name == 'push' && 'merge' || 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1
        with:
          version: v3.18.2
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - name: Show current version
        run: make get-version
      - name: Run helm
        run: make
  # TODO (degorenko): add push chart to helm repo later
